---
input_file: "data/util_data.csv"
output_file: "output/target_tracking_output.csv"
metrics_output_file: "output/target_tracking_metrics.csv"
initial_allocated_cores:
metrics: False
process_data_func: 'process_util_data'
time:
  granularity: 60
  cooldown: 6
  boot: 1
  warm_up:
    min: 9
    max: 12
policies:
  use: "target_tracking"
  reactive:
    src: "src/policies/reactive_static_policy.R"
    func: "reactive_static_policy"
    lower_bound: 25
    upper_bound: 50
    up_step_size: 16
    down_step_size: 4
    min_cap: 32
    max_cap: 240
  conservative: 
    src: "src/policies/conservative_static_policy.R"
    func: "conservative_static_policy"
    lower_bound: 25
    upper_bound: 50
    up_step_size: 16
    down_step_size: 4
    min_cap: 32
    max_cap: 240
    evaluation_period: 5
  target_tracking:
    src: "src/policies/target_tracking_policy.R"
    func: "target_tracking_policy"
    target_value: 40
    min_cap: 32
    max_cap: 240
    scale_up_cooldown: 2
    scale_down_cooldown: 8
    scale_in_threshold: 10
    vm_cores: 4
