---
input_file: "data/util_data.csv"
output_file: "output/simple_scaling_v2.csv"
metrics_output_file: "output/simple_scaling_v2_metrics.csv"
metrics: False
initial_allocated_cores:
process_data_func: 'process_util_data'
time: # TODO application
  granularity: 60
  warm_up:
    boot:
      min: 1
      max: 3
    startup:
      min: 6
      max: 9
policies:
  use: "simple_scaling" # TODO tirar use de policies
  simple_scaling:
    src: "src/policies/simple_scaling_policy.R"
    func: "simple_scaling_policy"
    lower_bound: 40
    upper_bound: 60
    step_type: "percentage"
    up_step_size: 0.3
    down_step_size: 0.2
    min_cap: 8
    max_cap: 64
    evaluation_period: 1
    cooldown: 4
  target_tracking:
    src: "src/policies/target_tracking_policy.R"
    func: "target_tracking_policy"
    target_value: 50
    min_cap: 8
    max_cap: 64
    scale_in_threshold: 10
    vm_cores: 4
    cooldown:
      up: 4
      down: 6
