---
input_file: "data/util_data.csv"
output_file: "output/simple_scaling.csv"
metrics_output_file: "output/simple_scaling_metrics.csv"
initial_allocated_cores:
metrics: True
process_data_func: 'process_util_data'
time:
  granularity: 60
  cooldown: 4
  boot: 1
  warm_up:
    min: 9
    max: 12
policies:
  use: "simple_scaling"
  simple_scaling:
    src: "src/policies/simple_scaling_policy.R"
    func: "simple_scaling_policy"
    lower_bound: 40
    upper_bound: 60
    up_step_size: 2
    down_step_size: 2
    min_cap: 8
    max_cap: 64
    evaluation_period: 1
  target_tracking:
    src: "src/policies/target_tracking_policy.R"
    func: "target_tracking_policy"
    target_value: 40
    min_cap: 32
    max_cap: 240
    scale_up_cooldown: 2
    scale_down_cooldown: 8
    scale_in_threshold: 10
    vm_cores: 4
