---
input_file: "path-to-input-file"
output_file: "path-to-output-file"
metrics_output_file: "path-to-output-metrics-file"
# Configs for master-data-api
initial_allocated_cores:
policies:
  use: "conservative"
  reactive:
    src: "src/policies/reactive_static_policy.R"
    fun: "reactive_static_policy"
    lower_bound: 25
    upper_bound: 50
    up_step_size: 16
    down_step_size: 4
    min_cap: 32
    max_cap: 240
    cooldown: 6
  conservative: 
    src: "src/policies/conservative_static_policy.R"
    fun: "conservative_static_policy"
    lower_bound: 25
    upper_bound: 50
    up_step_size: 16
    down_step_size: 4
    min_cap: 32
    max_cap: 240
    evaluation_period: 5
    cooldown: 6
    warm_up_lb: 9
    warm_up_ub: 12
