---
input_file: "path-to-input-file"
output_file: "path-to-output-file"
metrics_output_file: "path-to-output-metrics-file"
initial_allocated_cores:
time:
  granularity: 60
  cooldown: 6
  boot: 1
  warm_up:
    min: 9
    max: 12
policies:
  use: "conservative"
  reactive:
    src: "src/policies/reactive_static_policy.R"
    func: "reactive_static_policy"
    lower_bound: 25
    upper_bound: 50
    up_step_size: 16
    down_step_size: 4
    min_cap: 32
    max_cap: 240
  conservative: 
    src: "src/policies/conservative_static_policy.R"
    func: "conservative_static_policy"
    lower_bound: 25
    upper_bound: 50
    up_step_size: 16
    down_step_size: 4
    min_cap: 32
    max_cap: 240
    evaluation_period: 5
